// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mewzofaadhzsmbbhyrhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ld3pvZmFhZGh6c21iYmh5cmhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjQwNjAsImV4cCI6MjA3MzcwMDA2MH0.ldNBq0MzvKIHW7a3BQr1x0AGXgZsUzO3Md_SZo79srw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});